apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: grpc-health
    tier: backend
    deployedBy: deploy-node-app
  name: grpc-health
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grpc-health
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grpc-health
        tier: backend
        deployedBy: deploy-node-app
    spec:
      containers:
        - image: 'jefftian/grpc-health:4ca5b79-1575689002'
          imagePullPolicy: Always
          name: grpc-health
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 150m
              memory: 128Mi
            requests:
              cpu: 3m
              memory: 64Mi
          command:
            - node
            - dist/main.js
          envFrom: []
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

