apiVersion: v1
kind: Service
metadata:
  name: grpc-health-3001
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: grpc-health-3001.jeff-tian
      prefix: "/"
      service: http://grpc-health-3001.jeff-tian:3001
      host: grpc.jiwai.win
      timeout_ms: 30000
      use_websocket: true
spec:
  type: ClusterIP
  ports:
    - name: grpc-health-3001
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: grpc-health
    tier: backend
