apiVersion: v1
kind: Service
metadata:
  name: grpc-health
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: grpc-health
    tier: backend

