apiVersion: v1
kind: Service
metadata:
  name: grpc-health
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: grpc-health
    tier: backend
